[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12.1", features = ["json", "stream"] }
lol_html = "2.7.0"
dashmap = "6.1.0"
tantivy = "0.25.0"
url = "2.4"
anyhow = "1.0"
futures = "0.3"
bytes = "1.11.0"
clap = { version = "4.0", features = ["derive"] }
reqwest-middleware = "0.4.2"
reqwest-retry = "0.8.0"
#readability-rust = "0.1.0"
# get from git until the crate is updated or switch to dom_smoothie
readability-rust = { git = "https://github.com/dreampuf/readability-rust.git", branch = "main" }
rust-stemmers = "1.2.0"
